# Site settings
title: Identity
email: b.r.hendrick@gmail.com
description: The Jekyll version of the Identity theme by HTML5 UP.
baseurl: "/identity-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Brian Hendrick
your-title: agile aficionado - design thinker - product person

# Social settings
500px_url:
facebook_url: https://facebook.com
github_url:
instagram_url: https://instagram.com/rhymeswithzion
linkedin_url: https://www.linkedin.com/in/hendrickbrian
pinterest_url:
slack_url:
twitter_url: https://twitter.com/bhndrck

# Build settings
markdown: kramdown
